version: 1
disable_existing_loggers: true
formatters:
    default:
        format: '%(levelname)s:%(asctime)s [%(process)d] f=%(filename)s:%(lineno)d %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level: INFO
    filters: []
    stream: ext://sys.stdout
loggers:
  nginxlogprocessor:
    level: INFO
    handlers: [console,]
    propagate: no
root:
  level: INFO
  handlers: [console]